"""reset_db_fix_fk

Revision ID: 2d4d5a0e5223
Revises: 
Create Date: 2026-04-22 10:37:41.636530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4d5a0e5223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityStream', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ActivityStream_activity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Activity', ['activity_id'], ['activity_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ActivityStream', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ActivityStream_activity_id_fkey'), 'Activity', ['activity_id'], ['external_id'])

    # ### end Alembic commands ###
