"""fix grammar error

Revision ID: 6b5dbaf32712
Revises: 565e00b35ce4
Create Date: 2026-04-24 18:40:29.329657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b5dbaf32712'
down_revision = '565e00b35ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_zones', sa.JSON(), nullable=True))
        batch_op.drop_column('costome_zones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costome_zones', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('custom_zones')

    # ### end Alembic commands ###
