"""cambios en usuarios

Revision ID: 7f62130fdc49
Revises: 6b5dbaf32712
Create Date: 2026-04-29 08:58:02.088533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f62130fdc49'
down_revision = '6b5dbaf32712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), server_default='Male', nullable=False))
        batch_op.add_column(sa.Column('nickname', sa.String(), server_default='Hyrox runner', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('nickname')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
