"""Modificacion tabla predict y user para mejor ux

Revision ID: 88fed8580fd6
Revises: f9cb8c93ff9a
Create Date: 2026-05-05 08:05:50.853894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fed8580fd6'
down_revision = 'f9cb8c93ff9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PredictionLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('pred_5k', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pred_10k', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pred_21k', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pred_42k', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model_version', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('PredictionLog_last_activity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Activity', ['activity_id'], ['activity_id'])
        batch_op.drop_column('last_activity_id')
        batch_op.drop_column('estimated_time')
        batch_op.drop_column('date')
        batch_op.drop_column('obj_distance')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obj_distance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('obj_distance')

    with op.batch_alter_table('PredictionLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obj_distance', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('estimated_time', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_activity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('PredictionLog_last_activity_id_fkey'), 'Activity', ['last_activity_id'], ['activity_id'])
        batch_op.drop_column('model_version')
        batch_op.drop_column('pred_42k')
        batch_op.drop_column('pred_21k')
        batch_op.drop_column('pred_10k')
        batch_op.drop_column('pred_5k')
        batch_op.drop_column('created_at')
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###
