"""start_lat/lng null

Revision ID: 938cd98f81e6
Revises: b879c0d819c6
Create Date: 2026-05-09 19:09:58.245452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938cd98f81e6'
down_revision = 'b879c0d819c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.alter_column('start_lat',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
        batch_op.alter_column('start_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.alter_column('start_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
        batch_op.alter_column('start_lat',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)

    # ### end Alembic commands ###
