"""corregimos error birthdate

Revision ID: 9e005a3507b0
Revises: 7f62130fdc49
Create Date: 2026-04-29 12:22:54.199701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e005a3507b0'
down_revision = '7f62130fdc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
