"""Modificacion tabla user para añadir nivel del usuario

Revision ID: b879c0d819c6
Revises: 88fed8580fd6
Create Date: 2026-05-05 08:11:55.165162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b879c0d819c6'
down_revision = '88fed8580fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
