"""rename max_hr and add rest and zones

Revision ID: b9f6f6a94b4a
Revises: 2d4d5a0e5223
Create Date: 2026-04-22 14:22:32.773158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f6f6a94b4a'
down_revision = '2d4d5a0e5223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_hr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rest_hr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_edit', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('custom_zones', sa.JSON(), nullable=True))
        batch_op.drop_column('max_fc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_fc', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('custom_zones')
        batch_op.drop_column('last_edit')
        batch_op.drop_column('rest_hr')
        batch_op.drop_column('max_hr')

    # ### end Alembic commands ###
