"""add profile_photo

Revision ID: f9cb8c93ff9a
Revises: 9e005a3507b0
Create Date: 2026-05-01 17:04:18.929770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cb8c93ff9a'
down_revision = '9e005a3507b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
